In [ ]:
import numpy as np
import pandas as pd
from google.colab import files


In [ ]:
F = files.upload()

In [ ]:
df = pd.read_csv('/content/dermatology_database_1.csv')
df.head(36)

,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,scalp_involvement,...,disappearance_granular_layer,vacuolisation_damage_basal_layer,spongiosis,saw_tooth_appearance_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_mononuclear_infiltrate,band_like_infiltrate,age,Class
0,2,2,0,3,0,0,0,0,1,0,...,0,0,3,0,0,0,1,0,55,2
1,3,3,3,2,1,0,0,0,1,1,...,0,0,0,0,0,0,1,0,8,1
2,2,1,2,3,1,3,0,3,0,0,...,0,2,3,2,0,0,2,3,26,3
3,2,2,2,0,0,0,0,0,3,2,...,3,0,0,0,0,0,3,0,40,1
4,2,3,2,2,2,2,0,2,0,0,...,2,3,2,3,0,0,2,3,45,3
5,2,3,2,0,0,0,0,0,0,0,...,0,0,2,0,0,0,1,0,41,2
6,2,1,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,18,5
7,2,2,3,3,3,3,0,2,0,0,...,2,2,3,2,0,0,3,3,57,3
8,2,2,1,0,2,0,0,0,0,0,...,0,0,2,0,0,0,2,0,22,4
9,2,2,1,0,1,0,0,0,0,0,...,0,0,2,0,0,0,2,0,30,4


In [ ]:
df.shape


(366, 35)

In [ ]:
df['Class'].unique()

NameError: name 'df' is not defined

In [ ]:
mu = np.mean(df['Class'])
mu

2.80327868852459

In [ ]:
df.replace({'?': 36, 'NaN': 36},inplace = True)
df.loc[263]

erythema                                1
scaling                                 1
definite_borders                        1
itching                                 3
koebner_phenomenon                      0
polygonal_papules                       0
follicular_papules                      0
oral_mucosal_involvement                0
knee_and_elbow_involvement              0
scalp_involvement                       0
family_history                          0
melanin_incontinence                    0
eosinophils_infiltrate                  0
PNL_infiltrate                          0
fibrosis_papillary_dermis               3
exocytosis                              2
acanthosis                              3
hyperkeratosis                          1
parakeratosis                           2
clubbing_rete_ridges                    2
elongation_rete_ridges                  2
thinning_suprapapillary_epidermis       0
spongiform_pustule                      0
munro_microabcess                 

In [ ]:
mu = df.age.mean()
mu

36.2896174863388

In [ ]:
sigma =df.age.std()

In [ ]:
df['age' ] = (df['age'] - mu)/sigma

In [ ]:
df.age.mean()

-3.8827471899459027e-17

In [ ]:
#df['xo'] = 1
df.head()

,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,scalp_involvement,...,disappearance_granular_layer,vacuolisation_damage_basal_layer,spongiosis,saw_tooth_appearance_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_mononuclear_infiltrate,band_like_infiltrate,age,Class
0,2,2,0,3,0,0,0,0,1,0,...,0,0,3,0,0,0,1,0,1.234540,2
1,3,3,3,2,1,0,0,0,1,1,...,0,0,0,0,0,0,1,0,-1.866593,1
2,2,1,2,3,1,3,0,3,0,0,...,0,2,3,2,0,0,2,3,-0.678925,3
3,2,2,2,0,0,0,0,0,3,2,...,3,0,0,0,0,0,3,0,0.244817,1
4,2,3,2,2,2,2,0,2,0,0,...,2,3,2,3,0,0,2,3,0.574725,3


In [ ]:
df.age.std()

1.0

In [ ]:
x = df.drop(['Class'], axis= 1)
y = df.iloc[:,34]
x

,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,scalp_involvement,...,focal_hypergranulosis,disappearance_granular_layer,vacuolisation_damage_basal_layer,spongiosis,saw_tooth_appearance_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_mononuclear_infiltrate,band_like_infiltrate,age
0,2,2,0,3,0,0,0,0,1,0,...,0,0,0,3,0,0,0,1,0,1.234540
1,3,3,3,2,1,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,-1.866593
2,2,1,2,3,1,3,0,3,0,0,...,2,0,2,3,2,0,0,2,3,-0.678925
3,2,2,2,0,0,0,0,0,3,2,...,0,3,0,0,0,0,0,3,0,0.244817
4,2,3,2,2,2,2,0,2,0,0,...,2,2,3,2,3,0,0,2,3,0.574725
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,2,1,1,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,2,0,-0.744907
362,3,2,1,0,1,0,0,0,0,0,...,0,1,0,1,0,0,0,2,0,-0.019109
363,3,2,2,2,3,2,0,2,0,0,...,3,0,3,0,3,0,0,2,3,-0.546962
364,2,1,3,1,2,3,0,2,0,0,...,3,0,2,0,1,0,0,2,3,0.904632


In [ ]:
x_train, x_test = x[0:300], x[301:]
y_train, y_test = y[0:300], y[301:]
x_train.shape

(300, 34)

## K is the number of distinct classes



In [ ]:
df.iloc[:,34].unique()
k = 6



*w* is a 6 X 34 matrix



```
`# This is formatted as code`
```



In [ ]:
w = np.random.normal(loc = 0.0, scale = 1.0, size = (6,34))

w.shape,x_train.shape

((6, 34), (300, 34))

In [ ]:
def hypothesis(x_train,w,i):
  h_theta_x  = np.zeros(6)
  for k in range(6):
    h_theta_x[k] += np.exp(np.dot(w[k], x_train.loc[i]))
  sum = np.sum(h_theta_x)
  return h_theta_x/sum

In [ ]:
x_train.loc[262]

erythema                               2.000000
scaling                                1.000000
definite_borders                       0.000000
itching                                2.000000
koebner_phenomenon                     0.000000
polygonal_papules                      0.000000
follicular_papules                     0.000000
oral_mucosal_involvement               0.000000
knee_and_elbow_involvement             0.000000
scalp_involvement                      0.000000
family_history                         0.000000
melanin_incontinence                   0.000000
eosinophils_infiltrate                 0.000000
PNL_infiltrate                         0.000000
fibrosis_papillary_dermis              2.000000
exocytosis                             1.000000
acanthosis                             3.000000
hyperkeratosis                         2.000000
parakeratosis                          2.000000
clubbing_rete_ridges                   1.000000
elongation_rete_ridges                 3

In [ ]:
h = hypothesis(x_train,w,0)
h



array([6.59650871e-05, 6.61410592e-02, 1.51871523e-02, 1.23074081e-05,
       5.07641234e-02, 8.67829393e-01])

In [ ]:
def log_likelihood(x_train,y_train,w):
  l_theta = 0
  indicator = lambda y,l: 1 if y == l else 0
  epsilon = 1e-15
  m,n = x_train.shape
  k = w.shape[0]
  for i in range(m):
    h_theta = hypothesis(x_train,w,i)
    for j in range(k):
      l_theta = l_theta + (np.log(h_theta[j] + epsilon )*indicator(y_train[i],j))
  return l_theta




In [ ]:
l = log_likelihood(x_train,y_train,w)
l

-2130.721234362631

In [ ]:
def derivative1(x_train,y_train,w):
  m,n = x_train.shape
  K = w.shape[0]
  indicator = lambda y,l: 1 if y == l else 0
  dl_dw = np.zeros((w.shape))
  for i in range(m):
    h_theta = hypothesis(x_train,w,i)
    for j in range(K):
      h_theta_j = h_theta[j]
      indic_y_J = indicator(y_train[i],j)
      for k in range(n):
        dl_dw[j,k] += (indic_y_J - h_theta_j)*x_train.iloc[i,k]
  return dl_dw

In [ ]:
der1= derivative1(x_train,y_train,w)
der1


array([[-4.16822203e+01, -3.58412843e+01, -2.79280451e+01,
        -1.22964226e+01, -8.02540646e+00, -4.47579224e-06,
        -1.62035253e+01, -4.57577760e-06, -1.29053880e+01,
        -6.92467903e+00, -4.21756408e+00, -3.86829090e-06,
        -1.49670138e+00, -8.65106610e+00, -5.95102429e+00,
        -2.31539344e+01, -3.44401050e+01, -7.61417177e+00,
        -2.00499800e+01, -4.51168556e+00, -1.46662414e+01,
        -6.08621780e+00, -4.82905607e+00, -3.49033138e+00,
        -3.25702719e-01, -2.30182824e-01, -2.80027105e-04,
        -1.82932466e+01, -2.46140997e-02, -1.14976668e+01,
        -1.47939025e+01, -3.13512440e+01, -1.16670436e-01,
         1.73736655e+01],
       [ 1.49197211e+02,  1.57638155e+02,  1.61092785e+02,
         4.62767897e+01,  3.65106256e+01, -1.76751710e+00,
         2.16202316e+00, -1.71153691e+00,  1.37767473e+02,
         1.31035750e+02,  2.62473669e+01, -1.33018166e-01,
         9.18078154e-01,  1.03762355e+02, -7.84963490e+00,
        -1.96197320e+01,  1.42

In [ ]:
def derivative(x_train,y_train,w):
  m,n = x_train.shape
  K = w.shape[0]
  indicator = lambda y,l: 1 if y == l else 0
  dl_dw = np.zeros((w.shape))
  for j in range(K):
    for k in range(n):
      der = 0
      for i in range(m):
        h_theta = hypothesis(x_train,w,i)
        der += (indicator(y_train[i],j) - h_theta[j])*x_train.iloc[i,k]
      dl_dw[j,k] = der
  return dl_dw

In [ ]:
der = derivative(x_train,y_train,w)



array([[-4.16822203e+01, -3.58412843e+01, -2.79280451e+01,
        -1.22964226e+01, -8.02540646e+00, -4.47579224e-06,
        -1.62035253e+01, -4.57577760e-06, -1.29053880e+01,
        -6.92467903e+00, -4.21756408e+00, -3.86829090e-06,
        -1.49670138e+00, -8.65106610e+00, -5.95102429e+00,
        -2.31539344e+01, -3.44401050e+01, -7.61417177e+00,
        -2.00499800e+01, -4.51168556e+00, -1.46662414e+01,
        -6.08621780e+00, -4.82905607e+00, -3.49033138e+00,
        -3.25702719e-01, -2.30182824e-01, -2.80027105e-04,
        -1.82932466e+01, -2.46140997e-02, -1.14976668e+01,
        -1.47939025e+01, -3.13512440e+01, -1.16670436e-01,
         1.73736655e+01],
       [ 1.49197211e+02,  1.57638155e+02,  1.61092785e+02,
         4.62767897e+01,  3.65106256e+01, -1.76751710e+00,
         2.16202316e+00, -1.71153691e+00,  1.37767473e+02,
         1.31035750e+02,  2.62473669e+01, -1.33018166e-01,
         9.18078154e-01,  1.03762355e+02, -7.84963490e+00,
        -1.96197320e+01,  1.42

In [ ]:
der.shape


(6, 34)

In [ ]:
x_train.shape,w.shape

((300, 34), (6, 34))

In [ ]:
import math

In [ ]:
def soft_max(x_train,y_train,w,alpha,no_iters):
  hist_log_likelihood =[]
  for i in range(no_iters):
    dL_dw = derivative1(x_train,y_train,w)
    w += alpha*dL_dw
    hist_log_likelihood.append(log_likelihood(x_train,y_train,w))
    if i % math.ceil(no_iters/10)== 0:
      print(f"{i}th iteration ::  log_likelihood : {hist_log_likelihood[-1]}")
  return w,hist_log_likelihood[-1]


In [ ]:
no_iters = 100
alpha = 0.005
w_updated = [[-8.76943330e+00, -5.45924509e+00, -3.42582414e+00,
        -1.24827965e+00, -1.15460300e+00,  2.85860960e-01,
        -7.12498857e+00,  1.22463116e+00, -7.70905733e+00,
        -3.43547093e+00, -1.56646819e+00, -9.33635130e-01,
        -5.20455785e-01, -7.36464463e-01, -1.13876052e+00,
        -4.97188115e+00, -6.24248157e+00, -1.49945511e+00,
        -6.01197376e+00, -8.56174157e-01,  1.05915251e+00,
        -1.64148500e-01,  1.14395153e-01, -7.23222090e-01,
         6.44707105e-03, -5.25184211e-01, -1.31494714e+00,
        -4.75315962e+00, -5.17241095e-02, -5.30500050e+00,
        -6.04899650e+00, -5.28895496e+00, -7.41515622e-01,
         6.03148448e+00],
       [-7.45655755e+00, -3.86690138e+00, -8.96963072e-01,
        -5.03046804e+00,  1.39173149e+00, -2.46003350e+00,
        -1.20649375e+01, -2.14652803e+00, -1.61757032e+00,
         1.82796466e+00, -1.63345674e+00, -2.19092539e+00,
        -2.00587870e+00,  2.56714920e+00, -5.68492321e+00,
        -1.10948988e+01, -6.85455910e+00, -3.29871227e+00,
        -1.05112948e+00,  8.93894462e+00,  5.21524777e+00,
         1.13528200e+01,  4.51788768e+00,  5.52303568e+00,
        -2.25458361e+00,  4.19678188e+00, -2.04702648e+00,
        -1.08021205e+01, -4.39430616e+00, -6.43576885e+00,
        -6.85407640e+00, -5.62293009e+00, -3.08279187e+00,
         8.97974689e+00],
       [-5.31504441e+00, -1.66546735e+00, -5.21466914e+00,
         3.59770890e+00, -1.28416163e+01, -6.07207587e+00,
        -9.34969472e+00, -3.83652126e+00, -7.71108471e+00,
        -2.71884796e+00, -3.67530491e+00, -2.81069529e+00,
         4.50851235e+00,  1.11371015e+01, -7.05000632e+00,
        -1.36793780e+00, -6.76449817e+00, -7.08909167e+00,
        -7.37867670e+00, -2.24623406e+00, -3.87403860e+00,
        -1.97748527e+00,  6.95992743e-01, -3.77787800e-02,
        -3.45380887e+00, -5.12121649e+00, -4.30069342e+00,
         1.23331266e+00, -7.00219488e+00, -7.02438904e+00,
        -1.04931985e+01, -9.62823255e+00, -6.26146661e+00,
         6.27239896e+00],
       [-1.01080426e+01, -8.13541574e+00, -4.23629289e-01,
         1.46147466e+00,  1.05138312e+00,  1.14598274e+01,
        -8.18046414e+00,  1.10846455e+01, -6.41069291e+00,
        -2.80872343e+00, -2.94699319e+00,  1.06494871e+01,
        -5.93085623e-01, -4.91628294e+00, -2.13290761e-01,
        -6.49905922e+00, -5.60551721e+00, -3.65810049e+00,
        -2.63327954e+00, -2.11092902e+00, -1.09690614e+00,
        -1.06062960e+00, -2.83471377e+00, -7.33213178e-03,
         1.12036134e+01,  4.40669095e-01,  1.14034016e+01,
        -8.65808974e+00,  1.02755124e+01, -5.98185029e+00,
        -6.85899297e+00, -2.98999628e+00,  1.25664449e+01,
         6.00334136e+00],
       [-8.19949593e+00, -8.07315882e+00, -4.83909574e+00,
        -1.05190593e+01,  1.14854803e+01, -4.94995247e+00,
        -6.31382833e+00, -3.46459850e+00, -1.12901946e+01,
        -7.45468305e+00, -5.12724485e+00, -3.02462024e+00,
        -4.82583552e-01, -8.40017987e+00, -1.64859539e+00,
         5.87235184e+00, -9.07109727e+00, -2.02376882e+00,
        -5.93191137e+00, -9.61504486e+00, -9.13094256e+00,
        -5.99078883e+00, -4.35278657e+00, -2.00718878e+00,
        -4.06195722e+00,  1.46572140e+00, -4.62541404e+00,
         2.79521434e+00, -3.72731506e+00, -4.62676864e+00,
        -8.95224083e+00, -5.11856935e+00, -5.40007110e+00,
         7.63101299e+00],
       [-9.40797683e+00, -7.96982013e+00, -5.01961815e+00,
         2.34288727e+00, -2.04501084e+00, -4.38583750e-01,
        -6.30223924e+00, -1.39852955e+00, -7.18776163e+00,
        -3.83035388e+00, -1.15016274e+00,  9.55688350e-01,
        -8.97366354e-01, -5.89949059e+00,  1.39848051e+01,
        -7.62878566e+00, -1.66571739e+00, -1.12521252e+00,
        -5.43714766e+00, -2.50397826e+00,  7.82138558e+00,
        -3.05816246e+00, -1.47207236e+00, -6.55971531e-01,
         3.20059233e-01, -1.98537702e+00,  5.74036110e-01,
        -8.05874405e+00, -3.06109355e+00, -4.96058675e+00,
        -7.22291282e+00, -2.11649273e+00, -1.44300150e+00,
         6.95230324e+00]]
w_updated = np.array(w_updated)
w_optimal,optimal_log_likelihoood = soft_max(x_train,y_train,w_updated,alpha,no_iters)
w_optimal

0th iteration ::  log_likelihood : -19.254398037291722
10th iteration ::  log_likelihood : -18.55979063387432
20th iteration ::  log_likelihood : -17.889121996271697
30th iteration ::  log_likelihood : -17.236695479595767
40th iteration ::  log_likelihood : -16.598387415640108
50th iteration ::  log_likelihood : -15.971335753997472
60th iteration ::  log_likelihood : -15.353575594504607
70th iteration ::  log_likelihood : -14.743766300477843
80th iteration ::  log_likelihood : -14.141053331770584
90th iteration ::  log_likelihood : -13.54506372528349


array([[-1.12754848e+01, -7.57457610e+00, -4.81946925e+00,
        -1.77543932e+00, -1.15460528e+00,  2.85860960e-01,
        -1.00083567e+01,  1.22463116e+00, -1.01956955e+01,
        -3.87287013e+00, -2.17940050e+00, -9.33635130e-01,
        -5.20455798e-01, -8.24896314e-01, -1.13876052e+00,
        -6.66119201e+00, -7.84896220e+00, -2.58253250e+00,
        -7.76298410e+00, -9.23624187e-01,  1.05818748e+00,
        -1.64148500e-01,  1.14202820e-01, -7.23222112e-01,
        -8.17893512e-02, -5.25186181e-01, -1.31494714e+00,
        -5.89220116e+00, -5.17241317e-02, -7.43786976e+00,
        -8.74014419e+00, -7.18930517e+00, -7.41517577e-01,
         8.18005086e+00],
       [-1.00358534e+01, -5.86681939e+00, -2.39634037e+00,
        -5.97664183e+00,  1.38828806e+00, -2.46003350e+00,
        -1.50128710e+01, -2.14652803e+00, -4.18937485e+00,
         3.90370543e-01, -2.38571199e+00, -2.19092539e+00,
        -2.00587870e+00,  2.16647887e+00, -5.68492322e+00,
        -1.25962509e+01, -8.50

In [ ]:
i = 351
h = hypothesis(x_test,w_optimal,i)
h,h.argmax()


(array([4.63178263e-46, 1.00000000e+00, 5.87457661e-63, 4.21845930e-42,
        1.55689924e-85, 1.99518290e-44]),
 1)

In [ ]:
y_test.loc[351]

1

In [ ]:
count = 0
count_class6 = 0
false = 0
for i in range(0,366):
    h = hypothesis(x,w_optimal,i)
    actual = y.loc[i]
    if round(h.max()) == 1 :
      if actual == h.argmax():
        count += 1
      else:
        false += 1
    elif round(h.max()) != 1:
      count += 1
      count_class6 += 1
count

(347, 7, 19)

In [ ]:
347 + 7 + 19


373